### ISSUE TITLE
PDJ-F0022 session management in firefox anpassen

### ISSUE THREAD

**Issue by Tobaay** [Tobaay/pdj-music#22]

**Comment by Tobaay** [comment]
Fehler bei mir nicht reproduzierbar. Habe Firefox V 55.0 (64-Bit).

Fehler beim Logout in Chrome nicht passiert (auch nicht bei Gratla)

wenn eine neuere Version den Fehler behebt, wird das ticket wieder geschlossen.

versionsinfor unter menü rechts oben, dann fragezeichen und dann über firefox.

**Comment by Gratla** [comment]
Fehler bei mir noch vorhanden. Firefox V 54.0.1 (32-Bit). (Firefox sagt: "aktuelle Version")

**Comment by Gratla** [comment]
Bei Edge kommt der selbe Fehler! (Ja ich weiß, nd empfehlenswert)

**Comment by Tobaay** [comment]
Konnte den Fehler in Edge nachstellen. Schuld waren zwei required Felder, die in Edge und Firefox überprüft wurden, trotz der Tatsache, dass sie gerade gar nicht angezeigt wurden. Das waren die beiden Eingabefelder des Logins. Habe das required einfach weggenommen, da die login() Funktion sowieso sagt, dass man 1 Spast ist, wenn man etwas falsches eingibt.

**Comment by Tobaay** [comment]
dadurch konnte die action nicht weitergeleitet werden, was dazu geführt hat, dass gar nichts gecalled wurde.
